### ISSUE TITLE
Possible Issue with 'ExplicitInventoryByAgent'

### ISSUE THREAD

**Issue by FlanFlanagan** [cyclus/cymetric#104]
When I attempt to create frame using the following line I get the following error. 

>>> fname = cym.eval('ExplicitInventoryByAgent', db)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robert/.local/lib/python3.4/site-packages/cymetric/evaluator.py", line 82, in eval
    return e.eval(str(metric), conds=conds)
  File "/home/robert/.local/lib/python3.4/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/robert/.local/lib/python3.4/site-packages/cymetric/metrics.py", line 77, in __call__
    return f(series)
  File "/home/robert/.local/lib/python3.4/site-packages/cymetric/metrics.py", line 351, in explicit_inventory_by_agent
    inv = inv.groupby(level=inv_index).sum()
AttributeError: 'NoneType' object has no attribute 'groupby'

**Comment by opotowsky** [comment]
I'm wondering why the inv table is None here. Do you have the explicit inv table or the compact one, @FlanFlanagan?

**Comment by bam241** [comment]
@FlanFlanagan 
do you still have this issue ?
