### ISSUE TITLE
NOTETESTS RunTimeError with pyne/data.pyx

### ISSUE THREAD

**Issue by gyutaepark** [cyclus/cymetric#127]
Currently running Ubuntu 16.04 with latest develop of cyclus, cycamore, cymetric and pyne that I've built from source.

After installing cymetric in .local (where cyclus and cycamore are installed), when I run the tests as shown in Readme.md, I get the following error message. The simulation runs successfully.

```
Status: Cyclus run successful!
Output location: orig.sqlite
Simulation ID: f0ff2bbe-3ab4-4613-95bd-98a2c5451367
......../home/user/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: QAWarning: pyne.data is not yet QA compliant.
  return f(*args, **kwds)
/home/user/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: QAWarning: pyne.material is not yet QA compliant.
  return f(*args, **kwds)
/home/user/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: QAWarning: pyne.enrichment is not yet QA compliant.
  return f(*args, **kwds)
....../home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py:191: UserWarning: no faciity provided
  warnings.warn(wng_msg, UserWarning)
..EEEE..EEEE......EE......................................./home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py:133: UserWarning: no nuclide provided
  warnings.warn(wng_msg, UserWarning)
../home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py:163: UserWarning: no nuclide provided
  warnings.warn(wng_msg, UserWarning)
EE/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py:192: UserWarning: no nuclide provided
  warnings.warn(wng_msg, UserWarning)
EE..EEEE
======================================================================
ERROR: test_filters.test_inventories_activity(<cyclus.lib.Hdf5Back object at 0x7ffad1c2cd88>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 477, in test_inventories_activity
    cal = filters.inventories_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_filters.test_inventories_activity(<cyclus.lib.SqliteBack object at 0x7ffad1a090c8>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 477, in test_inventories_activity
    cal = filters.inventories_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_filters.test_inventories_decayheat(<cyclus.lib.Hdf5Back object at 0x7ffad1a1fe48>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 541, in test_inventories_decayheat
    cal = filters.inventories_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 240, in inventories_decayheat
    df = inventories_activity(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_filters.test_inventories_decayheat(<cyclus.lib.SqliteBack object at 0x7ffad1a1f3c8>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 541, in test_inventories_decayheat
    cal = filters.inventories_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 240, in inventories_decayheat
    df = inventories_activity(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_filters.test_transactions_activity(<cyclus.lib.Hdf5Back object at 0x7ffad1a11d88>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 290, in test_transactions_activity
    cal = filters.transactions_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 127, in transactions_activity
    compo = evaler.eval('Activity')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_filters.test_transactions_activity(<cyclus.lib.SqliteBack object at 0x7ffad1a02b88>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 290, in test_transactions_activity
    cal = filters.transactions_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 127, in transactions_activity
    compo = evaler.eval('Activity')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_filters.test_transactions_decayheat(<cyclus.lib.Hdf5Back object at 0x7ffad1c72508>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 358, in test_transactions_decayheat
    cal = filters.transactions_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 156, in transactions_decayheat
    compo = evaler.eval('DecayHeat')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 56, in eval
    d = self.eval(dep[0], conds=conds)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_filters.test_transactions_decayheat(<cyclus.lib.SqliteBack object at 0x7ffad1a21e88>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_filters.py", line 358, in test_transactions_decayheat
    cal = filters.transactions_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 156, in transactions_decayheat
    compo = evaler.eval('DecayHeat')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 56, in eval
    d = self.eval(dep[0], conds=conds)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_metrics.test_activity
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_metrics.py", line 195, in test_activity
    obs = metrics.activity.func(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_metrics.test_decayheat
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_metrics.py", line 222, in test_decayheat
    obs = metrics.decay_heat.func(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 183, in decay_heat
    val = (data.MeV_per_MJ * a * data.q_val(nuc))
  File "pyne/data.pyx", line 179, in pyne.data.q_val (/home/user/cyclus/pyne/build/pyne/data.cxx:3628)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_inventories_activity(<cyclus.lib.Hdf5Back object at 0x7ffad1a11ac8>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 193, in test_timeseries_inventories_activity
    cal = ts.inventories_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 165, in inventories_activity
    df = filters.inventories_activity(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_inventories_activity(<cyclus.lib.SqliteBack object at 0x7ffad1a1f1c8>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 193, in test_timeseries_inventories_activity
    cal = ts.inventories_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 165, in inventories_activity
    df = filters.inventories_activity(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_inventories_decayheat(<cyclus.lib.Hdf5Back object at 0x7ffad1a1fc88>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 231, in test_timeseries_inventories_decayheat
    cal = ts.inventories_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 194, in inventories_decayheat
    df = filters.inventories_decayheat(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 240, in inventories_decayheat
    df = inventories_activity(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_inventories_decayheat(<cyclus.lib.SqliteBack object at 0x7ffad1bdee88>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 231, in test_timeseries_inventories_decayheat
    cal = ts.inventories_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 194, in inventories_decayheat
    df = filters.inventories_decayheat(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 240, in inventories_decayheat
    df = inventories_activity(evaler, facilities, nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 219, in inventories_activity
    data.decay_const(int(row['NucId']))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_transactions_activity(<cyclus.lib.Hdf5Back object at 0x7ffad1d9a508>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 75, in test_timeseries_transactions_activity
    cal = ts.transactions_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 68, in transactions_activity
    nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 127, in transactions_activity
    compo = evaler.eval('Activity')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_transactions_activity(<cyclus.lib.SqliteBack object at 0x7ffad1a54688>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 75, in test_timeseries_transactions_activity
    cal = ts.transactions_activity(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 68, in transactions_activity
    nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 127, in transactions_activity
    compo = evaler.eval('Activity')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_transactions_decayheat(<cyclus.lib.Hdf5Back object at 0x7ffad1bde488>, 'test.h5', <class 'cyclus.lib.Hdf5Back'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 115, in test_timeseries_transactions_decayheat
    cal = ts.transactions_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 100, in transactions_decayheat
    nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 156, in transactions_decayheat
    compo = evaler.eval('DecayHeat')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 56, in eval
    d = self.eval(dep[0], conds=conds)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

======================================================================
ERROR: test_timeseries.test_timeseries_transactions_decayheat(<cyclus.lib.SqliteBack object at 0x7ffad1a64388>, 'test.sqlite', <class 'cyclus.lib.SqliteBack'>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/user/cyclus/cymetric/tests/test_timeseries.py", line 115, in test_timeseries_transactions_decayheat
    cal = ts.transactions_decayheat(evaler)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/timeseries.py", line 100, in transactions_decayheat
    nucs)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/filters.py", line 156, in transactions_decayheat
    compo = evaler.eval('DecayHeat')
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 56, in eval
    d = self.eval(dep[0], conds=conds)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/evaluator.py", line 59, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 76, in __call__
    return f(series)
  File "/home/user/anaconda3/lib/python3.6/site-packages/cymetric/metrics.py", line 150, in activity
    / data.atomic_mass(nuc))
  File "pyne/data.pyx", line 910, in pyne.data.decay_const (/home/user/cyclus/pyne/build/pyne/data.cxx:10735)
RuntimeError

----------------------------------------------------------------------
Ran 85 tests in 4.917s

FAILED (errors=18)
```

**Comment by bam241** [comment]
@gyutaepark do you still experience this ? (with the last develop version of Cymetric)

thx

**Comment by gyutaepark** [comment]
I've just tried after installing and do not get this error any more.
Thank you!

**Comment by bam241** [comment]
thank you for the update.

I close this then.

this should have been solve with #118
