### ISSUE TITLE
metrics filtering 

### ISSUE THREAD

**Issue by opotowsky** [cyclus/cymetric#24]
It seems I can filter on a root table just fine, but when I want to filter a metric, I get this type of error when trying to filter by any column other than QualId (pretty sure I tried all of the columns for the Materials metric):

```bash
$ cymetric lwr.sqlite -e "print(Materials[NucId != 922380000])"
/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/metrics.py:12: QAWarning: pyne.data is not yet QA compliant.
  from pyne import data
Traceback (most recent call last):
  File "/home/opotowsky/.local/bin/cymetric", line 4, in <module>
    main()
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/main.py", line 31, in main
    exec_code(ns.exec_code, db)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/execution.py", line 197, in exec_code
    exec(code, glb, loc)
  File "<string>", line 1, in <module>
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/execution.py", line 123, in __getitem__
    return self.evaler.eval(self.name, conds=conds)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/evaluator.py", line 59, in eval
    d = self.eval(dep[0], conds=conds)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/evaluator.py", line 62, in eval
    raw = m(series=series, conds=conds, known_tables=self.known_tables)
  File "/home/opotowsky/.local/lib/python2.7/site-packages/cymetric/root_metrics.py", line 27, in __call__
    return self.db.query(self.name, conds=conds)
  File "cyclus.pyx", line 123, in cymetric.cyclus._FullBackend.query (/home/opotowsky/cyclus/cymetric/build/cymetric/cyclus.cxx:2586)
RuntimeError: SQL error [SELECT * FROM Resources WHERE NucId != ?;]: no such column: NucId
```

**Comment by scopatz** [comment]
Just to double check.  Materials did not exist before, right? I think I know how to fix this.

**Comment by opotowsky** [comment]
Are you asking if Materials was in the db before I tried to filter it? I don't remember, trying again now

**Comment by scopatz** [comment]
Yeah, that is what I was asking. Sorry if that wasn't clear.

**Comment by opotowsky** [comment]
Confirmed: it does not work before or after Materials exists!

**Comment by scopatz** [comment]
Weird, this seems to be a SQL only issue.

**Comment by opotowsky** [comment]
I hate that you have more ammo in you anti-SQL war. I can't do HDF5 at home so I generally don't do it at all, otherwise I may have figured that out already!

**Comment by scopatz** [comment]
I am not on fighting SQL as a solution, just as the *only* solution -- which is easy because I am right :) 

More seriously, I have figured out what the issue is.

**Comment by opotowsky** [comment]
AWESOME*

*as long as the issue isn't too hairy

**Comment by opotowsky** [comment]
closed via https://github.com/cyclus/cymetric/pull/28
