### ISSUE TITLE
Install defaults different from cyclus

### ISSUE THREAD

**Issue by gidden** [cyclus/cymetric#48]
Cymetric should probably have the same install defaults as cyclus. A straight up install command fails for me.

```
$ ./setup.py install --user
Generating API Bindings...
/usr/bin/cmake
CMake command is
cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python
-- Cymetric platform defined as: __LINUX__
                  __________________________________________________________
                  |  ____  __   __ __  __  _____  _____   ____  ___  ____   |
             /    | |___ \ \ \ / /|  \/  ||____ ||_   _| / _  ||_ _||___ \  |
            /---, |     | | \ V / | |\/| |  |_  |  | |  | (_| | | |     | | |
       -----# ==| |  ___| |  | |  | |  | | ___| |  | |   > _  | | |  ___| | |
       | :) # ==| | |____/   |_|  |_|  |_||_____|  |_|  /_/ |_||___||____/  |
  -----'----#   | |_________________________________________________________|
  |)___()  '#   |______====____   \___________________________________|
 [_/,-,\"--"------ //,-,  ,-,\\\   |/             //,-,  ,-,  ,-,\\ __#
   ( 0 )|===******||( 0 )( 0 )||-  o              '( 0 )( 0 )( 0 )||
----'-'--------------'-'--'-'-----------------------'-'--'-'--'-'--------------

-- Build type: Release
-- PYTHON_EXECUTABLE: /usr/bin/python
-- Cython Version: Cython version 0.20.1
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so
-- Found SigC++ 
-- Found Glibmm 
-- Found LibXML++ 
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- A library with BLAS API found.
-- A library with LAPACK API found.
	Found LAPACK Libraries: /usr/lib/liblapack.so;/usr/lib/libblas.so
-- NUMPY_VERSION_STRING = 1.8.0
	COIN Root Dir: COIN_INCLUDE_DIR-NOTFOUND
-- COIN_ROOT_DIR hint is : 
-- Coin multiple library dependency status:
	COIN Include Dir: COIN_INCLUDE_DIR-NOTFOUND/coin
	COIN CBC: COIN_CBC_LIBRARY-NOTFOUND
	COIN CBC solver: COIN_CBC_SOLVER_LIBRARY-NOTFOUND
	COIN CGL: COIN_CGL_LIBRARY-NOTFOUND
	COIN CLP: COIN_CLP_LIBRARY-NOTFOUND
	COIN UTILS: COIN_COIN_UTILS_LIBRARY-NOTFOUND
	COIN OSI: COIN_OSI_LIBRARY-NOTFOUND
	COIN OSI CLP: COIN_OSI_CLP_LIBRARY-NOTFOUND
	COIN ZLIB: /usr/lib/x86_64-linux-gnu/libz.so
	COIN BZ2: /usr/lib/x86_64-linux-gnu/libbz2.so
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find COIN (missing: COIN_CBC_LIBRARY COIN_CBC_SOLVER_LIBRARY
  COIN_CGL_LIBRARY COIN_CLP_LIBRARY COIN_COIN_UTILS_LIBRARY COIN_OSI_LIBRARY
  COIN_OSI_CLP_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCOIN.cmake:124 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:78 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/home/gidden/work/cyclus/cymetric/build/CMakeFiles/CMakeOutput.log".
See also "/home/gidden/work/cyclus/cymetric/build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.

--------------------

If you are having issues building cymetric, please report your problem to cyclus-dev@googlegroups.com or look for help at http://fuelcycle.org

--------------------
Traceback (most recent call last):
  File "./setup.py", line 269, in <module>
    main()
  File "./setup.py", line 240, in main
    main_body(cmake_args, make_args)
  File "./setup.py", line 223, in main_body
    setup()
  File "./setup.py", line 149, in setup
    scripts = [os.path.join('scripts', f) for f in os.listdir('scripts')]
OSError: [Errno 2] No such file or directory: 'scripts'
```

**Comment by gidden** [comment]
The same lines for cyclus for me are

```
$ ./install.py 
/usr/bin/cmake
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done

-- Not Found Tcmalloc: Tcmalloc_LIBRARY-NOTFOUND
-- Found LibXml2: /usr/lib/x86_64-linux-gnu/libxml2.so (found version "2.9.1") 
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.40.2
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'sigc++-2.0'
--   found sigc++-2.0, version 2.2.10
-- Found SigC++ 
-- checking for module 'glibmm-2.4'
--   found glibmm-2.4, version 2.39.93
-- Found Glibmm 
-- checking for module 'libxml++-2.6'
--   found libxml++-2.6, version 2.36.0
-- Found LibXML++ 
/usr/lib/x86_64-linux-gnu/libxml2.so/usr/lib/libxml++-2.6.so/usr/lib/x86_64-linux-gnu/libxml2.so/usr/lib/x86_64-linux-gnu/libglibmm-2.4.so/usr/lib/x86_64-linux-gnu/libglib-2.0.so/usr/lib/x86_64-linux-gnu/libsigc-2.0.so
-- Found Sqlite3 header file in /usr/include
-- Found Sqlite3 libraries: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Found HDF5: /usr/lib/x86_64-linux-gnu/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   filesystem
--   system
--   serialization
--    Boost Root: 
--    Boost Include directory: /usr/include
--    Boost Library directories: /usr/lib/x86_64-linux-gnu
--    Boost Program Options location: /usr/lib/x86_64-linux-gnu/libboost_program_options.so
--    Boost System location: /usr/lib/x86_64-linux-gnu/libboost_system.so
--    Boost Filesystem location: /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
--    Boost Serialization location: /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
	Found LAPACK Libraries: /usr/lib/liblapack.so;/usr/lib/libblas.so
	COIN Root Dir: 
-- COIN_ROOT_DIR hint is : 
-- Coin multiple library dependency status:
	COIN Include Dir: /home/gidden/.local/include/coin
	COIN CBC: /home/gidden/.local/lib/libCbc.so
	COIN CBC solver: /home/gidden/.local/lib/libCbcSolver.so
	COIN CGL: /home/gidden/.local/lib/libCgl.so
	COIN CLP: /home/gidden/.local/lib/libClp.so
	COIN UTILS: /home/gidden/.local/lib/libCoinUtils.so
	COIN OSI: /home/gidden/.local/lib/libOsi.so
	COIN OSI CLP: /home/gidden/.local/lib/libOsiClp.so
	COIN ZLIB: /usr/lib/x86_64-linux-gnu/libz.so
	COIN BZ2: /usr/lib/x86_64-linux-gnu/libbz2.so
-- Found COIN: /home/gidden/.local/include/coin  
-- Found COIN Include Dirs: /home/gidden/.local/include/coin
```

**Comment by scopatz** [comment]
Weird, mine seem to be finding the same thing: https://gist.github.com/scopatz/52f206d27e15371fe10e

**Comment by gidden** [comment]
I looks like all your deps are from conda installs, whereas mine are from
source

On Thu, Apr 2, 2015 at 10:55 AM, Anthony Scopatz <notifications@github.com>
wrote:

> Weird, mine seem to be finding the same thing:
> https://gist.github.com/scopatz/52f206d27e15371fe10e
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cymetric/issues/48#issuecomment-88956588>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
Sure, but I don't think that was true on the machine that I originally developed all of this stuff on.  Also, I don't think that it is true on the cloud server I have running for Denia. This might be the root cause, but I bet there is something else going on too.

**Comment by opotowsky** [comment]
Sorry I'm late to this convo. I'm not sure what is going on here. I install from source and don't have a problem.

**Comment by gidden** [comment]
yes, but how did you install your dependences (e.g., coin, etc.)?

On Wed, Apr 15, 2015 at 4:47 PM, opotowsky <notifications@github.com> wrote:

> Sorry I'm late to this convo. I'm not sure what is going on here. I
> install from source and don't have a problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cymetric/issues/48#issuecomment-93578345>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by opotowsky** [comment]
both ways!

Here's mine:
```
$ ./setup.py install --user -j7
Generating API Bindings...
/usr/bin/cmake
CMake command is
cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python
-- Cymetric platform defined as: __LINUX__
                  __________________________________________________________
                  |  ____  __   __ __  __  _____  _____   ____  ___  ____   |
             /    | |___ \ \ \ / /|  \/  ||____ ||_   _| / _  ||_ _||___ \  |
            /---, |     | | \ V / | |\/| |  |_  |  | |  | (_| | | |     | | |
       -----# ==| |  ___| |  | |  | |  | | ___| |  | |   > _  | | |  ___| | |
       | :) # ==| | |____/   |_|  |_|  |_||_____|  |_|  /_/ |_||___||____/  |
  -----'----#   | |_________________________________________________________|
  |)___()  '#   |______====____   \___________________________________|
 [_/,-,\"--"------ //,-,  ,-,\\\   |/             //,-,  ,-,  ,-,\\ __#
   ( 0 )|===******||( 0 )( 0 )||-  o              '( 0 )( 0 )( 0 )||
----'-'--------------'-'--'-'-----------------------'-'--'-'--'-'--------------

-- Build type: Release
-- PYTHON_EXECUTABLE: /usr/bin/python
-- Cython Version: Cython version 0.21.1
-- Found glib-2.0: /usr/include/glib-2.0, /usr/lib/x86_64-linux-gnu/libglib-2.0.so
-- Found SigC++ 
-- Found Glibmm 
-- Found LibXML++ 
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- A library with BLAS API found.
-- A library with LAPACK API found.
	Found LAPACK Libraries: /usr/lib/liblapack.so;/usr/lib/libblas.so
-- NUMPY_VERSION_STRING = 1.8.2
	COIN Root Dir: /usr/include
-- COIN_ROOT_DIR hint is : 
-- Coin multiple library dependency status:
	COIN Include Dir: /usr/include/coin
	COIN CBC: /usr/lib/x86_64-linux-gnu/libCbc.so
	COIN CBC solver: /usr/lib/x86_64-linux-gnu/libCbcSolver.so
	COIN CGL: /usr/lib/x86_64-linux-gnu/libCgl.so
	COIN CLP: /usr/lib/x86_64-linux-gnu/libClp.so
	COIN UTILS: /usr/lib/x86_64-linux-gnu/libCoinUtils.so
	COIN OSI: /usr/lib/x86_64-linux-gnu/libOsi.so
	COIN OSI CLP: /usr/lib/x86_64-linux-gnu/libOsiClp.so
	COIN ZLIB: /usr/lib/x86_64-linux-gnu/libz.so
	COIN BZ2: /usr/lib/x86_64-linux-gnu/libbz2.so
-- Found COIN Include Dirs: /usr/include/coin
-- Using /home/opotowsky/.local as CYCLUS_ROOT_DIR.
-- Found Cyclus Core Headers : /home/opotowsky/.local/include/cyclus
-- Found Cyclus Core Test Headers : /home/opotowsky/.local/include/cyclus
-- Found Cyclus Core Shared Data : /home/opotowsky/.local/share/cyclus
-- Found Cyclus Core Library : /home/opotowsky/.local/lib/libcyclus.so
-- Found Cyclus Test Libraries : /home/opotowsky/.local/lib/libgtest.so/home/opotowsky/.local/lib/cyclus/libbaseagentunittests.so
-- CMake Install Prefix: /usr/local
-- RPATH: $ORIGIN/lib
-- Include paths for /home/opotowsky/cyclus/cymetric/cymetric: /usr/lib/python2.7/dist-packages/numpy/core/include;/usr/include;/usr/include/libxml++-2.6;/usr/include/glibmm-2.4;/usr/lib/x86_64-linux-gnu/glibmm-2.4/include;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/sigc++-2.0;/usr/lib/x86_64-linux-gnu/sigc++-2.0/include;/usr/lib/libxml++-2.6/include;/usr/include;/usr/include/coin;/home/opotowsky/.local/include/cyclus
-- Include paths for /home/opotowsky/cyclus/cymetric: /usr/lib/python2.7/dist-packages/numpy/core/include;/usr/include;/usr/include/libxml++-2.6;/usr/include/glibmm-2.4;/usr/lib/x86_64-linux-gnu/glibmm-2.4/include;/usr/include/glib-2.0;/usr/lib/x86_64-linux-gnu/glib-2.0/include;/usr/include/sigc++-2.0;/usr/lib/x86_64-linux-gnu/sigc++-2.0/include;/usr/lib/libxml++-2.6/include;/usr/include;/usr/include/coin;/home/opotowsky/.local/include/cyclus
-- Copying C/C++ header files.
-- Copying Cython header files.
-- Copying scripts.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/opotowsky/cyclus/cymetric/build
[ 50%] Built target cyclus
[100%] Built target typesystem
[100%] Built target ReplicatePythonSourceTree
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /home/opotowsky/.local/bin/cymetric to 775
running install_data
running install_egg_info
Removing /home/opotowsky/.local/lib/python2.7/site-packages/cymetric-0.0_dev.egg-info
Writing /home/opotowsky/.local/lib/python2.7/site-packages/cymetric-0.0_dev.egg-info

NOTE: If you have not done so already, please be sure that your PATH and LD_LIBRARY_PATH (or DYLD_FALLBACK_LIBRARY_PATH on Mac OSX) has been appropriately set to the install prefix of cymetric. For this install of cymetric you may add the following lines to your '~/.bashrc' file or equivalent:

# Cymetric Environment Settings
export PATH="/home/opotowsky/.local/bin:${PATH}"
export LD_LIBRARY_PATH="/home/opotowsky/.local/lib:${LD_LIBRARY_PATH}"
```
